#!/bin/sh

if [ ! -z $1 ];then
    lock=$1
else
    lock=1200
fi
if [ ! -z $2 ];then
    end=$2
else
    end=1200
fi
# Only exported variables can be used within the timer's command.
export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

# Run xidlehook
xidlehook \
  `# Don't lock when there's a fullscreen application` \
  --not-when-fullscreen \
  `# Don't lock when there's audio playing` \
  --not-when-audio \
  `# Dim the screen after 10 minutes, undim if user becomes active` \
  --timer $lock \
    'slock' \
    '' \
  `# Finally, suspend 30 min after it locks` \
  --timer $end \
    'systemctl suspend' \
    ''
