#!/bin/sh
case "$(printf "a selected area\\ncurrent window\\nfull screen\\ngif\\n" | dmenu -l 4 -i -p "Screenshot which area?")" in
	"a selected area") maim -su | xclip -selection clipboard -t image/png ;;
	"current window") maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
	"full screen") maim | xclip -selection clipboard -t image/png ;;
    "gif") peek;;
esac
