#!/bin/sh
case "$(printf "a selected area\\ncurrent window\\nfull screen\\n" | dmenu -l 3 -i -p "Screenshot which area?")" in
	"a selected area") maim -s | xclip -selection clipboard -t image/png ;;
	"current window") maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
	"full screen") maim | xclip -selection clipboard -t image/png ;;
esac
