#!/bin/sh

current=`cat /sys/class/backlight/amdgpu_bl0/brightness`

case $1 in
    "dec")change=`echo "$current - 15" | bc`;;
    "inc")change=`echo "$current + 15" | bc`;;
esac

if [ $change -lt 0 ]
then
    echo "0" | sudo tee /sys/class/backlight/amdgpu_bl0/brightness
else
    echo $change | sudo tee /sys/class/backlight/amdgpu_bl0/brightness
fi
