#!/bin/sh

className=`ls ~/Documents/ | dmenu`

[ -z $className ] && exit

bspc desktop -f \^3 && $TERMINAL -e $EDITOR $HOME/Documents/$className/Notes.tex&
zathura $HOME/Documents/$className/Notes.pdf&
